# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta_update do
    version = get_version_number(xcodeproj: "SoccerInfo.xcodeproj")
    build_app(workspace: "SoccerInfo.xcworkspace", scheme: "SoccerInfo")
    puts "#{version} 빌드 완료"

    upload_to_testflight
    puts "#{version} 테스트 플라이트 업로드 완료"

    upload_symbols_to_crashlytics(gsp_path: "./SoccerInfo/GoogleService-Info.plist")
    puts "#{version} Crashlytics dSYM 업로드 완료"

    create_pull_request(
      repo: "JD-man/FootballInfo",
      title: "새 버전 PR",
      base: "develop",
      body: "main으로 새 버전 PR"
    )
    puts "#{version} develop PR 완료"

    create_pull_request(
      repo: "JD-man/FootballInfo",
      title: "새 버전 PR",
      base: "main",
      body: "main으로 새 버전 PR"
    )
    puts "#{version} main PR 완료"
  end
end
